#!/bin/sh

DAT=`mktemp`
CMD=`mktemp`

trap "rm -f $DAT $CMD" EXIT INT

sed -ne '/^gnuplot:/ s/.*: //p' motion.log > $DAT

cat <<EOF > $CMD
set xrange [0:3]
set yrange [0:2.1]
set grid
set multiplot layout 3,1
plot '$DAT' using 2:3 title "XY"
set xrange [*:*]
set yrange [*:*]
plot '$DAT' using 1:4 title "ang [rad]"
plot '$DAT' using 1:2 title "X [m]",\
     '$DAT' using 1:3 title "Y [m]"
unset multiplot
pause -1
EOF

gnuplot $CMD

